opt_type: "gsdiff_sd15_chibi"

optimizer:
  name: "adamw"
  lr: 2.0e-5
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.01
  eps: 1.e-8

lr_scheduler:
  name: "cosine_warmup"
  num_warmup_steps: 50

train:
  batch_size_per_gpu: 1
  epochs: 500
  log_freq: 1
  early_eval_freq: 10
  eval_freq: 100
  save_freq: 200
  eval_freq_epoch: 10
  save_freq_epoch: 50
  ema_kwargs:
    decay: 0.999
    use_ema_warmup: true
    inv_gamma: 1.
    power: 0.75
  early_eval: 50

opt:
  view_concat_condition: true
  input_concat_binary_mask: true
  prediction_type: "v_prediction"
  rendering_loss_prob: 0.5
  snr_gamma: 5.0

ui:
  load_pretrained_model: "gsdiff_gobj83k_sd15_image__render"

val:
  batch_size_per_gpu: 1
